name: Build USQUE Windows x64

# 手动触发
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Build static Windows binary
        run: |
          echo "开始编译 Windows 64 位静态二进制"
          export CGO_ENABLED=0
          GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o usque_windows_amd64.exe main.go
          echo "编译完成"

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: usque-windows-binary
          path: usque_windows_amd64.exe
